/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export {FormBuilder as FormBuilder_1} from '@angular/forms/src/form_builder';
import * as import0 from '@angular/core';
import * as import1 from './builder.component';
class SVFormBuilderInjector extends import0.ɵNgModuleInjector<import1.SVFormBuilder> {
  _SVFormBuilder_0:import1.SVFormBuilder;
  constructor(parent:import0.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  createInternal():import1.SVFormBuilder {
    this._SVFormBuilder_0 = new import1.SVFormBuilder();
    return this._SVFormBuilder_0;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import1.SVFormBuilder)) { return this._SVFormBuilder_0; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const SVFormBuilderNgFactory:import0.NgModuleFactory<import1.SVFormBuilder> = new import0.NgModuleFactory<any>(SVFormBuilderInjector,import1.SVFormBuilder);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvRWR1YXJkby9zb3VyY2UvcmVwb3MvTEFCMTUuQTUuU2VydmVyVmFsaWRhdGVkRm9ybS9zcmMvcGxhdGZvcm0vc3ZhbGlkYXRlZC9idWlsZGVyLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9Vc2Vycy9FZHVhcmRvL3NvdXJjZS9yZXBvcy9MQUIxNS5BNS5TZXJ2ZXJWYWxpZGF0ZWRGb3JtL3NyYy9wbGF0Zm9ybS9zdmFsaWRhdGVkL2J1aWxkZXIuY29tcG9uZW50LnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
