/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export {FormControl as FormControl_1} from '@angular/forms/src/model';
import * as import0 from '@angular/core';
import * as import1 from './control.component';
class SVFormControlInjector extends import0.ɵNgModuleInjector<import1.SVFormControl> {
  _SVFormControl_0:import1.SVFormControl;
  constructor(parent:import0.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  createInternal():import1.SVFormControl {
    this._SVFormControl_0 = new import1.SVFormControl();
    return this._SVFormControl_0;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import1.SVFormControl)) { return this._SVFormControl_0; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const SVFormControlNgFactory:import0.NgModuleFactory<import1.SVFormControl> = new import0.NgModuleFactory<any>(SVFormControlInjector,import1.SVFormControl);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvRWR1YXJkby9zb3VyY2UvcmVwb3MvTEFCMTUuQTUuU2VydmVyVmFsaWRhdGVkRm9ybS9zcmMvcGxhdGZvcm0vc3ZhbGlkYXRlZC9mb3JtQ29udHJvbC9jb250cm9sLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9Vc2Vycy9FZHVhcmRvL3NvdXJjZS9yZXBvcy9MQUIxNS5BNS5TZXJ2ZXJWYWxpZGF0ZWRGb3JtL3NyYy9wbGF0Zm9ybS9zdmFsaWRhdGVkL2Zvcm1Db250cm9sL2NvbnRyb2wuY29tcG9uZW50LnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
